# Generated by Django 5.2.17 on 2026-09-15 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('type', models.CharField(choices=[('tv', 'Télévision'), ('radio', 'Radio')], default='tv', max_length=10)),
                ('logo', models.URLField(blank=True, help_text="Lien vers le logo (pas d'ImageField).")),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'chaîne',
                'db_table': 'programmation_chaine',
            },
        ),
        migrations.CreateModel(
            name='Grille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_validation', 'En validation'), ('validee', 'Validée')], default='brouillon', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('chaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grilles', to='programmation.chaine')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grilles_creees', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grilles_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'grille',
                'db_table': 'programmation_grille',
            },
        ),
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('info', 'Information'), ('divertissement', 'Divertissement'), ('sport', 'Sport'), ('culture', 'Culture'), ('musique', 'Musique'), ('religion', 'Religion'), ('jeunesse', 'Jeunesse'), ('talk', 'Talk-show'), ('serie', 'Série'), ('magazine', 'Magazine'), ('autre', 'Autre')], default='autre', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('heure_debut', models.DateTimeField()),
                ('heure_fin', models.DateTimeField()),
                ('image_affiche', models.URLField(blank=True, help_text="Lien vers l'affiche affichée sur le frontend (ex. https://balafon.media/images/c-le-matin.jpg).", null=True)),
                ('fiabilite', models.CharField(choices=[('confirme', 'Confirmé'), ('estime', 'Estimé')], default='estime', max_length=20)),
                ('grille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissions', to='programmation.grille')),
            ],
            options={
                'verbose_name': 'émission',
                'db_table': 'programmation_emission',
                'ordering': ['heure_debut'],
            },
        ),
        migrations.AddConstraint(
            model_name='grille',
            constraint=models.CheckConstraint(condition=models.Q(('date_fin__gte', models.F('date_debut'))), name='grille_date_fin_apres_debut'),
        ),
        migrations.AddConstraint(
            model_name='emission',
            constraint=models.CheckConstraint(condition=models.Q(('heure_fin__gt', models.F('heure_debut'))), name='emission_heure_fin_apres_debut'),
        ),
    ]
