# Generated by Django 5.0.14 on 2026-09-02 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='grille',
            name='grille_periode_valide',
        ),
        migrations.AddField(
            model_name='chaine',
            name='logo',
            field=models.URLField(blank=True, help_text="Lien vers le logo (pas d'ImageField)."),
        ),
        migrations.AddField(
            model_name='emission',
            name='fiabilite',
            field=models.CharField(choices=[('confirme', 'Confirmé'), ('estime', 'Estimé')], default='estime', max_length=20),
        ),
        migrations.AddField(
            model_name='emission',
            name='image_affiche',
            field=models.URLField(blank=True, help_text="Lien vers l'affiche affichée sur le frontend (ex. https://balafon.media/images/c-le-matin.jpg).", null=True),
        ),
        migrations.AlterField(
            model_name='chaine',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='emission',
            name='genre',
            field=models.CharField(choices=[('info', 'Information'), ('divertissement', 'Divertissement'), ('sport', 'Sport'), ('culture', 'Culture'), ('musique', 'Musique'), ('religion', 'Religion'), ('jeunesse', 'Jeunesse'), ('talk', 'Talk-show'), ('serie', 'Série'), ('magazine', 'Magazine'), ('autre', 'Autre')], default='autre', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='grille',
            constraint=models.CheckConstraint(check=models.Q(('date_fin__gte', models.F('date_debut'))), name='grille_date_fin_apres_debut'),
        ),
        migrations.AlterModelTable(
            name='chaine',
            table='programmation_chaine',
        ),
        migrations.AlterModelTable(
            name='emission',
            table='programmation_emission',
        ),
        migrations.AlterModelTable(
            name='grille',
            table='programmation_grille',
        ),
    ]
