# Generated by Django 5.0.14 on 2026-09-01 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
            ],
        ),
    ]
