# Generated by Django 5.0.14 on 2026-09-16 10:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programmation', '0005_remove_sqlite_incompatible_emission_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleveAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instant', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('spectateurs', models.PositiveIntegerField(default=0)),
                ('emission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves_audience', to='programmation.emission')),
            ],
            options={
                'verbose_name': "relevé d'audience",
                'verbose_name_plural': "relevés d'audience",
                'db_table': 'audience_releve',
                'ordering': ['-instant'],
                'indexes': [models.Index(fields=['emission', '-instant'], name='audience_re_emissio_c3fdc6_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle_session', models.CharField(db_index=True, max_length=64)),
                ('empreinte', models.CharField(blank=True, help_text='Hachage tronqué IP+user-agent, non réversible.', max_length=32)),
                ('premier_battement', models.DateTimeField(default=django.utils.timezone.now)),
                ('dernier_battement', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('battements', models.PositiveIntegerField(default=1)),
                ('emission', models.ForeignKey(blank=True, help_text='Émission suivie au moment du battement (null hors antenne).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions_audience', to='programmation.emission')),
            ],
            options={
                'verbose_name': "session d'audience",
                'verbose_name_plural': "sessions d'audience",
                'db_table': 'audience_session',
                'indexes': [models.Index(fields=['emission', 'dernier_battement'], name='audience_se_emissio_ce0b09_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='sessionaudience',
            constraint=models.UniqueConstraint(fields=('cle_session', 'emission'), name='audience_une_session_par_emission'),
        ),
    ]
