# Generated by Django 5.0.14 on 2026-09-21 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programmation', '0005_remove_sqlite_incompatible_emission_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('modification_derniere_minute', 'Modification dernière minute'), ('grille_incomplete', 'Grille incomplète'), ('validation', 'Validation de grille'), ('synchro_vmix', 'Synchronisation vMix'), ('autre', 'Autre')], default='autre', max_length=40)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('statut_lecture', models.BooleanField(default=False)),
                ('destinataire', models.ForeignKey(blank=True, help_text='Diffuseur destinataire (null = tous les diffuseurs de la chaîne).', limit_choices_to={'role': 'diffuseur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('emission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programmation.emission')),
                ('grille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='programmation.grille')),
            ],
            options={
                'verbose_name': 'alerte',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
