# Generated by Django 5.0.14 on 2026-09-21 02:27

import comptes.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_alter_utilisateur_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
                ('objects', comptes.models.UtilisateurManager()),
            ],
        ),
    ]
